
import java.awt.Desktop;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import org.json.JSONException;
import org.json.JSONObject;

import parser.ParserUtil;

import common.ExtensionConst;
import common.Global;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author AngryPotato
 */
@SuppressWarnings("serial")
public class Window extends javax.swing.JFrame {

    /**
     * 文件选择窗口
     *
     */
    private JFileChooser fileChooser = new JFileChooser();
    
    /**
     * 当前选择的目录
     * */
    private File selecteDir;

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        readConfig();
        updateViewConfig();
        initFileChooser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gRadioGroup = new javax.swing.ButtonGroup();
        gTxtFileDr = new javax.swing.JTextField();
        gBtnSelect = new javax.swing.JButton();
        btnCreatJson = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        gRadioNoFromat = new javax.swing.JRadioButton();
        gRadioGroup.add(jRadioButton1);
        gRadioGroup.add(gRadioNoFromat);
        btnCreateExcel = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnWatchExcel = new javax.swing.JButton();
        btnWatchJson = new javax.swing.JButton();
        Global.registerJButton(btnCreateExcel);
        Global.registerJButton(gBtnSelect);
        Global.registerJButton(btnCreatJson);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gTxtFileDr.setToolTipText("Excel或JSON目录");

        gBtnSelect.setText("选择");
        gBtnSelect.setActionCommand("btnSelect");
        gBtnSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClickSelectHandler(evt);
            }
        });

        btnCreatJson.setText("生成JSON");
        btnCreatJson.setActionCommand("btnCreateJSON");
        btnCreatJson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClickCreateJSONHandler(evt);
            }
        });

        jLabel1.setText("Excel或JSON所在目录");

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("输出格式化JSON");
        jRadioButton1.setActionCommand("jsonFormat");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        gRadioNoFromat.setText("输出非格式化JSON");
        gRadioNoFromat.setActionCommand("jsonFormat");

        btnCreateExcel.setText("生成Excel");
        btnCreateExcel.setActionCommand("btnCreateExcel");
        btnCreateExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClickCreateExcelHandler(evt);
            }
        });

        btnHelp.setText("帮助");
        btnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClickHelpHandler(evt);
            }
        });

        btnWatchExcel.setText("查看Excel模版");
        btnWatchExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClickWatchExcelHandler(evt);
            }
        });

        btnWatchJson.setText("查看JSON模版");
        btnWatchJson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClickWatchJSONHandler(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gTxtFileDr, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gBtnSelect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(gRadioNoFromat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnWatchExcel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreatJson)
                                .addGap(98, 98, 98)
                                .addComponent(btnCreateExcel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnHelp)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnWatchJson)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gTxtFileDr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gBtnSelect)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gRadioNoFromat)
                    .addComponent(btnWatchExcel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addGap(10, 10, 10)
                .addComponent(btnWatchJson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreatJson, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCreateExcel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHelp)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 初始化文件过滤器 目前只允许选择目录
     */
    private void initFileChooser() {
//        FileNameExtensionFilter filter = new FileNameExtensionFilter(
//                "Excel", "xls", "xlsm", "xlsx");
//
//        fileChooser.setFileFilter(filter);
//        filter = new FileNameExtensionFilter("JSON", "json");
//        fileChooser.addChoosableFileFilter(filter);
//        fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    }

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * 点击了生成json按钮
     * */
    private void onClickCreateJSONHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClickCreateJSONHandler
        // TODO add your handling code here:
    	saveConfig();
        if(selecteDir != null)
        {
        	Global.setWindowEnable(false);
            ParserUtil.parse(selecteDir.listFiles(), ExtensionConst.EXCEL_TYPE);
        }
    }//GEN-LAST:event_onClickCreateJSONHandler

    /**
     * 点击了选择按钮, 弹出选择目录窗体
     *
     */
    private void onClickSelectHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClickSelectHandler
        // TODO add your handling code here:
        fileChooser.showOpenDialog(this);
        selecteDir = fileChooser.getSelectedFile();
        Global.file_path = selecteDir.getPath().replace("\\", "\\\\");
        updateViewConfig();
    }//GEN-LAST:event_onClickSelectHandler
    
    /**
     * 保存配置
     * */
    private void saveConfig()
    {
    	File file = new File(Window.class.getResource("").getPath()+Global.config_path);
    	if(file.exists() == false)
    	{
    		try {
				file.createNewFile();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				JOptionPane.showMessageDialog(null, "创建配置文件失败");
				return;
			}
    	}
		FileWriter writer;
		try {
			writer = new FileWriter(file);
			String jsonStr = "{\n" +
								"\tdelay:"+Global.delay+",\n" +
								"\tjsonFormat:"+jRadioButton1.isSelected()+",\n" +
								"\tpath:\""+Global.file_path+"\"\n" +
							"}";
			writer.write(jsonStr);
			writer.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
    }
    
    /**
     * 读取配置
     * */
    private void readConfig()
    {
    	File file = new File(Window.class.getResource("").getPath()+Global.config_path);
    	if(file.exists() == false)
    	{
    		return;
    	}
    	BufferedReader reader = null;
		String dataStr = "";
		try {
			reader = new BufferedReader(new FileReader(file));
			String tempString = null;
			// 一次读入一行，直到读入null为文件结束
			while ((tempString = reader.readLine()) != null) {
				// 显示行号
				dataStr = dataStr.concat(tempString);
			}
			reader.close();
			JSONObject json = new JSONObject(dataStr);
			Global.file_path = json.getString("path").replace("\\", "\\\\");
			Global.export_json_format = json.getBoolean("jsonFormat");
			updateViewConfig();
		} catch (IOException e) {
			e.printStackTrace();
		} catch (JSONException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "配置文件数据不正确!");
		} finally {
			if (reader != null) {
				try {
					reader.close();
				} catch (IOException e1) {
				}
			}
		}
    }
    
    /**
     * 更新界面上的配置显示
     * */
    private void updateViewConfig()
    {
    	this.gTxtFileDr.setText(Global.file_path);
    	this.jRadioButton1.setSelected(Global.export_json_format);
    	this.selecteDir = new File(Global.file_path);
    }

    /**
     * 点击了生成Excel按钮
     *
     */
    private void onClickCreateExcelHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClickCreateExcelHandler
        // TODO add your handling code here:
    	saveConfig();
        if(selecteDir != null)
        {
        	Global.setWindowEnable(false);
        	
            ParserUtil.parse(selecteDir.listFiles(), ExtensionConst.JSON_TYPE);
        }
    }//GEN-LAST:event_onClickCreateExcelHandler

    
    /**
     * 点击了帮助按钮
     * */
    private void onClickHelpHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClickHelpHandler
    	try {
    		Desktop.getDesktop().open(new File(Window.class.getResource("").getPath()+Global.readMe_path));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, "无法自动打开,请手动打开\n"+Window.class.getResource("").getPath()+Global.readMe_path);
		}
    }//GEN-LAST:event_onClickHelpHandler

    private void onClickWatchJSONHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClickWatchJSONHandler
        // TODO add your handling code here:
        try {
    		 Desktop.getDesktop().open(new File(Window.class.getResource("").getPath()+"etc/test.json"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, "无法自动打开,请手动打开\n"+Window.class.getResource("").getPath()+"etc/test.json");
		}
       
    }//GEN-LAST:event_onClickWatchJSONHandler

    private void onClickWatchExcelHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClickWatchExcelHandler
        // TODO add your handling code here:
         try {
    		 Desktop.getDesktop().open(new File(Window.class.getResource("").getPath()+"\\etc\\test.xls"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, "无法自动打开,请手动打开\n"+Window.class.getResource("").getPath()+"\\etc\\test.xls");
		}
    }//GEN-LAST:event_onClickWatchExcelHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup gRadioGroup;
    private javax.swing.JButton gBtnSelect;
    private javax.swing.JButton btnCreatJson;
    private javax.swing.JButton btnCreateExcel;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnWatchExcel;
    private javax.swing.JButton btnWatchJson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton gRadioNoFromat;
    private javax.swing.JTextField gTxtFileDr;
    // End of variables declaration//GEN-END:variables
}
